services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: grant_access
      MINIO_ROOT_PASSWORD: ai_food_analysing
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - allergydetect_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: /bin/sh
    command: >
      -c "ollama serve & sleep 5 && 
      (ollama list | grep qwen3-vl:4b || ollama pull qwen3-vl:4b) && 
      wait"
    restart: unless-stopped
    networks:
      - allergydetect_network

  backend:
    build: ./python-app
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=grant_access
      - MINIO_SECRET_KEY=ai_food_analysing
      - MINIO_BUCKET_NAME=ingredients
      - MINIO_SECURE=false
      - DATABASE_PATH=/app/data/app.db
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - CORS_ORIGINS=http://localhost:3000
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=development
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - backend_data:/app/data
      - ./python-app:/app
    depends_on:
      - minio
      - ollama
    restart: unless-stopped
    networks:
      - allergydetect_network

  frontend:
    build: ./react-app
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - allergydetect_network

volumes:
  minio_data:
  ollama_data:
  backend_data:

networks:
  allergydetect_network:
    driver: bridge
    name: allergydetect_network